name: monopoly_deal
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  rive: ^0.9.1
  firebase_core: ^1.24.0
  tiled: ^0.9.0
  collection: ^1.16.0
  flame: ^1.4.0
  flame_svg: ^1.6.0
  flame_rive: ^1.5.2
  flame_tiled: ^1.8.0
  meta: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/tiles/
