name: lucky_deal_server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  collection: ^1.17.0
  dart_frog: ^0.3.0
  dart_frog_web_socket: ^0.1.0-dev.1
  equatable: ^2.0.5
  hashids2: ^2.0.0
  logging: ^1.1.0
  lucky_deal_shared:
    path: ./lucky_deal_shared
  redis: ^3.1.0
  uuid: ^3.0.7

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
  web_socket_client: ^0.1.0-dev.1
